### ISSUE TITLE
[Bug]: helix start dev fails with Docker volume mount error on fresh repo checkout

### ISSUE THREAD

**Issue by mantrakp04** [HelixDB/helix-db#617]
### What happened?

Starting the Helix local instance immediately after cloning the repository fails; Docker cannot bind the volume defined at `packages/helix-db/.helix/.volumes/dev` even though the path should exist. The CLI-generated compose file references a host directory that is ignored in Git and missing by default.  
- **Environment**: WSL2 (Linux 6.6.87.2-microsoft-standard-WSL2) inside `/home/barrel/V2`, Docker Desktop with WSL integration (local engine).  
- **Expected**: Helix CLI creates any required host directories, `docker compose` starts `helix-helix-db-dev_app`, and the instance listens on port 6969.  
- **Actual**: Docker aborts during container creation with “failed to populate volume… mount … .helix/.volumes/dev … no such file or directory”; the Helix CLI reports `Failed to start instance`.  

### Steps to reproduce

clone the repo → `cd /home/barrel/V2/packages/helix-db` → run `helix start dev`

### Version

Helix CLI 2.0.1

### Environment

Self-hosted

### Relevant log output

```shell
Failed to start instance:
 Container helix-helix-db-dev_app  Creating
 Container helix-helix-db-dev_app  Error response from daemon: failed to populate volume: error while mounting volume '/var/lib/docker/volumes/helix-helix-db-dev_helix_helix_db_dev_data/_data': failed to mount local volume: mount /home/barrel/V2/packages/helix-db/.helix/.volumes/dev:/var/lib/docker/volumes/helix-helix-db-dev_helix_helix_db_dev_data/_data, flags: 0x1000: no such file or directory
```

**Comment by xav-db** [comment]
on it!

**Comment by matthewsanetra** [comment]
Hello! Thanks for reporting. We saw a similar issue during testing but this was fixed by updating Docker Desktop.

Could you please tell me your current Docker Desktop version then try updating (if it's not latest)?

**Comment by mantrakp04** [comment]
updated from `4.45.0 (203075)` to `4.47.0` but the issue still persists

**Comment by xav-db** [comment]
hey man, apologies for this, it seems to be a windows/wsl specific issue. 

if you git clone from this branch https://github.com/HelixDB/helix-db/tree/wsl-docker-fixes and build from source using

`cd helix-cli && sh build.sh dev` 

this should fix things

**Comment by mantrakp04** [comment]
```sh
Rust is not installed. Installing Rust...
/home/barrel/.cargo/bin/rustc
info: downloading installer
warn: It looks like you have an existing rustup settings file at:
warn: /home/barrel/.rustup/settings.toml
warn: Rustup will install the default toolchain as specified in the settings file,
warn: instead of the one inferred from the default host triple.
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warn: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.90.0 (1159e78c4 2025-09-14)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, you need to source
the corresponding env file under $HOME/.cargo.

This is usually done by running one of the following (note the leading DOT):
. "$HOME/.cargo/env"            # For sh/bash/zsh/ash/dash/pdksh
source "$HOME/.cargo/env.fish"  # For fish
source $"($nu.home-path)/.cargo/env.nu"  # For nushell
build.sh: 10: source: not found
    Updating crates.io index
     Locking 0 packages to latest compatible versions
note: pass `--verbose` to see 7 unchanged dependencies behind latest
warning: /home/barrel/V2/packages/helix-db/helix-db/helix-db/Cargo.toml: file `/home/barrel/V2/packages/helix-db/helix-db/helix-db/benches/hnsw_benches.rs` found to be present in multiple build targets:
  * `integration-test` target `hnsw_benches`
  * `bench` target `hnsw_benches`
warning: /home/barrel/V2/packages/helix-db/helix-db/helix-db/Cargo.toml: file `/home/barrel/V2/packages/helix-db/helix-db/helix-db/benches/bm25_benches.rs` found to be present in multiple build targets:
  * `integration-test` target `bm25_benches`
  * `bench` target `bm25_benches`
   Compiling openssl-sys v0.9.109
   Compiling hyper v1.7.0
   Compiling icu_locale_core v2.0.0
   Compiling icu_collections v2.0.0
   Compiling digest v0.10.7
   Compiling lmdb-master3-sys v0.2.5
   Compiling aead v0.5.2
   Compiling pest_derive v2.8.2
   Compiling self-replace v1.5.0
   Compiling dotenvy v0.15.7
   Compiling toml v0.9.7
   Compiling heed3 v0.22.0
   Compiling sha1 v0.10.6
   Compiling tungstenite v0.27.0
warning: openssl-sys@0.9.109: Could not find directory of OpenSSL installation, and this `-sys` crate cannot proceed without this knowledge. If OpenSSL is installed and this crate had trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the compilation process. See stderr section below for further information.
error: failed to run custom build command for `openssl-sys v0.9.109`

Caused by:
  process didn't exit successfully: `/home/barrel/V2/packages/helix-db/helix-db/target/debug/build/openssl-sys-00a4cb8f4f1da36a/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-check-cfg=cfg(osslconf, values("OPENSSL_NO_OCB", "OPENSSL_NO_SM4", "OPENSSL_NO_SEED", "OPENSSL_NO_CHACHA", "OPENSSL_NO_CAST", "OPENSSL_NO_IDEA", "OPENSSL_NO_CAMELLIA", "OPENSSL_NO_RC4", "OPENSSL_NO_BF", "OPENSSL_NO_PSK", "OPENSSL_NO_DEPRECATED_3_0", "OPENSSL_NO_SCRYPT", "OPENSSL_NO_SM3", "OPENSSL_NO_RMD160", "OPENSSL_NO_EC2M", "OPENSSL_NO_OCSP", "OPENSSL_NO_CMS", "OPENSSL_NO_COMP", "OPENSSL_NO_SOCK", "OPENSSL_NO_STDIO", "OPENSSL_NO_EC", "OPENSSL_NO_SSL3_METHOD", "OPENSSL_NO_KRB5", "OPENSSL_NO_TLSEXT", "OPENSSL_NO_SRP", "OPENSSL_NO_RFC3779", "OPENSSL_NO_SHA", "OPENSSL_NO_NEXTPROTONEG", "OPENSSL_NO_ENGINE", "OPENSSL_NO_BUF_FREELISTS", "OPENSSL_NO_RC2"))
  cargo:rustc-check-cfg=cfg(openssl)
  cargo:rustc-check-cfg=cfg(libressl)
  cargo:rustc-check-cfg=cfg(boringssl)
  cargo:rustc-check-cfg=cfg(awslc)
  cargo:rustc-check-cfg=cfg(libressl250)
  cargo:rustc-check-cfg=cfg(libressl251)
  cargo:rustc-check-cfg=cfg(libressl252)
  cargo:rustc-check-cfg=cfg(libressl261)
  cargo:rustc-check-cfg=cfg(libressl270)
  cargo:rustc-check-cfg=cfg(libressl271)
  cargo:rustc-check-cfg=cfg(libressl273)
  cargo:rustc-check-cfg=cfg(libressl280)
  cargo:rustc-check-cfg=cfg(libressl281)
  cargo:rustc-check-cfg=cfg(libressl291)
  cargo:rustc-check-cfg=cfg(libressl310)
  cargo:rustc-check-cfg=cfg(libressl321)
  cargo:rustc-check-cfg=cfg(libressl332)
  cargo:rustc-check-cfg=cfg(libressl340)
  cargo:rustc-check-cfg=cfg(libressl350)
  cargo:rustc-check-cfg=cfg(libressl360)
  cargo:rustc-check-cfg=cfg(libressl361)
  cargo:rustc-check-cfg=cfg(libressl370)
  cargo:rustc-check-cfg=cfg(libressl380)
  cargo:rustc-check-cfg=cfg(libressl381)
  cargo:rustc-check-cfg=cfg(libressl382)
  cargo:rustc-check-cfg=cfg(libressl390)
  cargo:rustc-check-cfg=cfg(libressl400)
  cargo:rustc-check-cfg=cfg(libressl410)
  cargo:rustc-check-cfg=cfg(ossl101)
  cargo:rustc-check-cfg=cfg(ossl102)
  cargo:rustc-check-cfg=cfg(ossl102f)
  cargo:rustc-check-cfg=cfg(ossl102h)
  cargo:rustc-check-cfg=cfg(ossl110)
  cargo:rustc-check-cfg=cfg(ossl110f)
  cargo:rustc-check-cfg=cfg(ossl110g)
  cargo:rustc-check-cfg=cfg(ossl110h)
  cargo:rustc-check-cfg=cfg(ossl111)
  cargo:rustc-check-cfg=cfg(ossl111b)
  cargo:rustc-check-cfg=cfg(ossl111c)
  cargo:rustc-check-cfg=cfg(ossl111d)
  cargo:rustc-check-cfg=cfg(ossl300)
  cargo:rustc-check-cfg=cfg(ossl310)
  cargo:rustc-check-cfg=cfg(ossl320)
  cargo:rustc-check-cfg=cfg(ossl330)
  cargo:rustc-check-cfg=cfg(ossl340)
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR


  Could not find openssl via pkg-config:
  Could not run `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openssl`
  The pkg-config command could not be found.

  Most likely, you need to install a pkg-config package for your OS.
  Try `apt install pkg-config`, or `yum install pkg-config`, or `brew install pkgconf`
  or `pkg install pkg-config`, or `apk add pkgconfig` depending on your distribution.

  If you've already installed it, ensure the pkg-config command is one of the
  directories in the PATH environment variable.

  If you did not expect this build to link to a pre-installed system library,
  then check documentation of the openssl-sys crate for an option to
  build the library from source, or disable features or dependencies
  that require pkg-config.

  cargo:warning=Could not find directory of OpenSSL installation, and this `-sys` crate cannot proceed without this knowledge. If OpenSSL is installed and this crate had trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the compilation process. See stderr section below for further information.

  --- stderr


  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.109


  It looks like you're compiling on Linux and also targeting Linux. Currently this
  requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
  could not be found. If you have OpenSSL installed you can likely fix this by
  installing `pkg-config`.


warning: build failed, waiting for other jobs to finish...
barrel@MSI:~/V2/packages/helix-db/helix-db/helix-cli$ sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev build-essential && . "$HOME/.cargo/env" && cd /home/barrel/V2/packages/helix-db/helix-db/helix-cli && cargo build --locked | cat
[sudo] password for barrel: 
Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                             
Get:3 https://packages.stripe.dev/stripe-cli-debian-local stable InRelease [4276 B]                                                                       
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease                                                                              
Hit:5 http://archive.ubuntu.com/ubuntu noble InRelease                                          
Hit:6 https://pkg.cloudflare.com/cloudflared any InRelease                
Get:7 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Hit:8 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Get:9 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1444 kB]
Get:10 http://archive.ubuntu.com/ubuntu noble-updates/main Translation-en [282 kB]
Fetched 1856 kB in 2s (1145 kB/s)                               
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.10ubuntu1).
The following additional packages will be installed:
  libpkgconf3 pkgconf pkgconf-bin
Suggested packages:
  libssl-doc
The following NEW packages will be installed:
  libpkgconf3 libssl-dev pkg-config pkgconf pkgconf-bin
0 upgraded, 5 newly installed, 0 to remove and 103 not upgraded.
Need to get 2483 kB of archives.
After this operation, 13.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 libpkgconf3 amd64 1.8.1-2build1 [30.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libssl-dev amd64 3.0.13-0ubuntu3.5 [2408 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble/main amd64 pkgconf-bin amd64 1.8.1-2build1 [20.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble/main amd64 pkgconf amd64 1.8.1-2build1 [16.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble/main amd64 pkg-config amd64 1.8.1-2build1 [7264 B]
Fetched 2483 kB in 1s (1776 kB/s)    
Selecting previously unselected package libpkgconf3:amd64.
(Reading database ... 54053 files and directories currently installed.)
Preparing to unpack .../libpkgconf3_1.8.1-2build1_amd64.deb ...
Unpacking libpkgconf3:amd64 (1.8.1-2build1) ...
Selecting previously unselected package libssl-dev:amd64.
Preparing to unpack .../libssl-dev_3.0.13-0ubuntu3.5_amd64.deb ...
Unpacking libssl-dev:amd64 (3.0.13-0ubuntu3.5) ...
Selecting previously unselected package pkgconf-bin.
Preparing to unpack .../pkgconf-bin_1.8.1-2build1_amd64.deb ...
Unpacking pkgconf-bin (1.8.1-2build1) ...
Selecting previously unselected package pkgconf:amd64.
Preparing to unpack .../pkgconf_1.8.1-2build1_amd64.deb ...
Unpacking pkgconf:amd64 (1.8.1-2build1) ...
Selecting previously unselected package pkg-config:amd64.
Preparing to unpack .../pkg-config_1.8.1-2build1_amd64.deb ...
Unpacking pkg-config:amd64 (1.8.1-2build1) ...
Setting up libpkgconf3:amd64 (1.8.1-2build1) ...
Setting up libssl-dev:amd64 (3.0.13-0ubuntu3.5) ...
Setting up pkgconf-bin (1.8.1-2build1) ...
Setting up pkgconf:amd64 (1.8.1-2build1) ...
Setting up pkg-config:amd64 (1.8.1-2build1) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.6) ...
warning: /home/barrel/V2/packages/helix-db/helix-db/helix-db/Cargo.toml: file `/home/barrel/V2/packages/helix-db/helix-db/helix-db/benches/hnsw_benches.rs` found to be present in multiple build targets:
  * `integration-test` target `hnsw_benches`
  * `bench` target `hnsw_benches`
warning: /home/barrel/V2/packages/helix-db/helix-db/helix-db/Cargo.toml: file `/home/barrel/V2/packages/helix-db/helix-db/helix-db/benches/bm25_benches.rs` found to be present in multiple build targets:
  * `integration-test` target `bm25_benches`
  * `bench` target `bm25_benches`
   Compiling openssl-sys v0.9.109
   Compiling hyper-util v0.1.17
   Compiling icu_provider v2.0.0
   Compiling tokio-tungstenite v0.27.0
   Compiling openssl v0.10.73
   Compiling native-tls v0.2.14
   Compiling icu_normalizer v2.0.0
   Compiling icu_properties v2.0.1
   Compiling idna_adapter v1.2.1
   Compiling idna v1.1.0
   Compiling hyper-rustls v0.27.7
   Compiling axum v0.8.6
   Compiling url v2.5.7
   Compiling tokio-native-tls v0.3.1
   Compiling hyper-tls v0.6.0
   Compiling reqwest v0.12.23
   Compiling helix-metrics v0.1.1 (/home/barrel/V2/packages/helix-db/helix-db/metrics)
   Compiling self_update v0.42.0
   Compiling helix-db v1.0.139 (/home/barrel/V2/packages/helix-db/helix-db/helix-db)
   Compiling helix-cli v2.0.1 (/home/barrel/V2/packages/helix-db/helix-db/helix-cli)
warning: unused import: `std::borrow::Cow`
 --> helix-cli/src/docker.rs:5:5
  |
5 | use std::borrow::Cow;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `helix-cli` (bin "helix") generated 1 warning (run `cargo fix --bin "helix"` to apply 1 suggestion)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 22.03s
barrel@MSI:~/V2/packages/helix-db/helix-db/helix-cli$ cd ..
barrel@MSI:~/V2/packages/helix-db/helix-db$ cd ..
barrel@MSI:~/V2/packages/helix-db$ ls
db  helix-db  helix.toml
barrel@MSI:~/V2/packages/helix-db$ helix dev push
error: unrecognized subcommand 'dev'

Usage: helix <COMMAND>

For more information, try '--help'.
barrel@MSI:~/V2/packages/helix-db$ helix push dev
[DEPLOY] Deploying local instance 'dev'
[BUILD] Building instance 'dev'
[UPDATE] Updating Helix repository cache...
[SUCCESS] Helix repository updated
[PREPARE] Preparing workspace for 'dev'
[COPY] Copied cached repo to /home/barrel/V2/packages/helix-db/.helix/dev/helix-repo-copy
[COMPILE] Compiling Helix queries...
[CODEGEN] Generating Rust code from Helix queries...
queries_path: /home/barrel/V2/packages/helix-db/./db/
got files: 2
[PARSE] Parsing Helix files...
[ANALYZE] Analyzing Helix files...
[SUCCESS] Helix queries compiled to Rust files
[DOCKER] Generating Docker configuration...
[SUCCESS] Docker configuration generated
[DOCKER] Building image for instance 'dev'...
[DOCKER] Image built successfully
[SUCCESS] Instance 'dev' built successfully
[DOCKER] Starting instance 'dev'...
Failed to start instance:
 Container helix-helix-db-dev_app  Creating
 Container helix-helix-db-dev_app  Error response from daemon: failed to populate volume: error while mounting volume '/var/lib/docker/volumes/helix-helix-db-dev_helix_helix_db_dev_data/_data': failed to mount local volume: mount /home/barrel/V2/packages/helix-db/.helix/.volumes/dev:/var/lib/docker/volumes/helix-helix-db-dev_helix_helix_db_dev_data/_data, flags: 0x1000: no such file or directory
Error response from daemon: failed to populate volume: error while mounting volume '/var/lib/docker/volumes/helix-helix-db-dev_helix_helix_db_dev_data/_data': failed to mount local volume: mount /home/barrel/V2/packages/helix-db/.helix/.volumes/dev:/var/lib/docker/volumes/helix-helix-db-dev_helix_helix_db_dev_data/_data, flags: 0x1000: no such file or directory

barrel@MSI:~/V2/packages/helix-db$ 
```

**Comment by xav-db** [comment]
we've since merged a fix! if you run `cargo uninstall helix-cli` then run `curl -sSL https://install.helix-db.com | bash` and then do `helix push dev` hopefully that should now work.

**Comment by xav-db** [comment]
> clone the repo → cd /home/barrel/V2/packages/helix-db → run helix start dev 

also just to ask why are you doing this

**Comment by xav-db** [comment]
http://localhost:3001/documentation/cli-v2/getting-started

**Comment by xav-db** [comment]
https://docs.helix-db.com/documentation/cli-v2/getting-started

**Comment by mantrakp04** [comment]
ahh its just the folder name the repo is in helix-db/helix-db/

**Comment by xav-db** [comment]
not 100% sure what this means?
